script: |
  # Change to the target directory
  cd /opt/caguar/
  
  # List files with detailed info
  ls -ltr

  # Debugging: Check if the file exists before attempting to move
  if [ -f tracker-servergit ]; then
    echo "tracker-servergit found"
  else
    echo "tracker-servergit not found"
  fi

  # Rename the old file, if it exists
  if [ -f tracker-server ]; then
    mv tracker-server tracker-server-old || echo "Failed to rename tracker-server"
  else
    echo "tracker-server not found"
  fi

  # Move the new file into place
  if [ -f tracker-servergit ]; then
    mv tracker-servergit tracker-server || echo "Failed to move tracker-servergit"
  else
    echo "tracker-servergit not found"
  fi
