name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            # Copy the zip file to the target directory
            sudo cp -r buildgit.zip /opt/caguar2/
            
            # Change to the target directory
            cd /opt/caguar2/
            
            # Unzip the new build
            sudo unzip buildgit.zip
            
            # Move the existing 'modern' directory to 'modern-old'
            sudo mv modern modern-old
            
            # Rename the extracted directory to 'modern'
            sudo mv build modern

            # List contents after unzip
            ls -l
            
