name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Copy the new build file to /opt/caguar/
            cp -r buildgit.zip /opt/caguar2/

            # Change to the /opt/caguar/ directory
            cd /opt/caguar2/

            # List files to verify the copied build file is present
            ls 

            # Rename the existing 'modern' directory to 'modern26'
            mv modern modern-old

            # List files to verify the renaming was successful
            ls -ltr

            # Unzip the new build file
            unzip buildgit.zip

            # Rename the unzipped directory to 'modern'
            mv build modern

         
